siemens/ix

- CHANGELOG.md
- package.json
- packages/aggrid/package.json
- packages/angular-test-app/package.json
- packages/angular/package.json
- packages/core/package.json
- packages/documentation/docs/installation/CHANGELOG.md
- packages/documentation/package.json
- packages/echarts/package.json
- packages/react-test-app/package.json
- packages/react/package.json
> chore: bump ix version to 1.0.0-beta.4

- packages/core/src/components/menu-item/menu-item.scss
Preventing the text inside menu items to be selected by user leads to less confusion when clicking on respective items since no text hightlighting will get shown. It is rather unlikely that the user will want to select the menu text to e.g. copy/paste it.
> fix(core/menu-item): prevent text selection

- packages/core/src/components/application-header/application-header.tsx
- packages/core/src/index.html
Load default siemens logo if brand theme related svg is existing
> feat(core/appliaction-header): load optional application logo

- packages/angular-test-app/src/preview-examples/tree-custom.ts
- packages/angular/src/tree/tree.ts
- packages/core/src/components/tree-item/tree-item.scss
- packages/documentation/docs/auto-generated/previews/angular/tree-custom.md
- packages/documentation/docs/auto-generated/previews/react/tree-custom.md
- packages/documentation/docs/auto-generated/previews/web-component/tree-custom.md
- packages/html-test-app/package.json
- packages/html-test-app/src/preview-examples/tree-custom.html
- packages/react-test-app/src/preview-examples/tree-custom.tsx
- packages/react/src/tree/tree.tsx
> fix(core/tree-item): replace with tree-item custom properties

- README.md
- package.json
changed the license badge to the one used by some other MIT license products at siemens. Also changed license type in package.json to "MIT" to simplify the work of license scanning tools.
> docs: nicer MIT license badge

- packages/core/stencil.config.ts
When running **build** for the _@siemens/ix_ package the file **component-doc.json** generates its content _eol_ based on the users system.
To uniformize the content from win/unix systems i added a search replace "\r" -> ""
Runned the build command on both unix & win systems and the output is the same
> fix(core): eol uniformization

- packages/core/component-doc.json
- packages/core/src/components/date-picker/date-picker.tsx
- packages/core/src/components/my-component/my-component.tsx
Fix the problem on date picker where the months and the years would not change. A condition was made to prevent this bug to happen again.
Works correctly now.
Fix #136 
Tested locally
> fix(core/datepicker): date picker months and years

- packages/core/scss/components/_button-group.scss
Now when in a group, every button doesnt have a right border exepect the last one.
Fix #151 
Tested locally
> fix(core): button group borders

- packages/core/src/components/select/select.tsx
- packages/core/src/components/select/test/cw-select.spec.tsx
If a label of `ix-select-item` is changed the input element was not updated.
Iam added a MutationObserver to observe child changes regarding label
> fix(core/select): observer child label change

- packages/documentation/src/pages/index.module.scss
- packages/documentation/src/pages/index.tsx
Buttons have no space to the sides.
When at a specific screen size that has no more space to the sides of the left and right button, the buttons now get this new positions.
Tested locally
> fix(documentation): fix buttons responsiveness

- .github/workflows/build.yml
Currently when you create a pull request 2 build actions are triggered
When creating a merge request there should only be 1 build action
> ci(workflow/build): avoid duplicated pipeline on merge

- packages/core/src/components/date-picker/date-picker.tsx
If you deselect the the date on the datepicker and press done a js issue is thrown because there is no null check on the toFormat function
Null check before the toFormat call
> fix(core/date-picker): handle empty from date

- packages/core/src/components/toast/toast.tsx
Put scaling into `requestAnimationFrame` to be sure that `onTransitionEnd` event is triggered properly.
> fix(core/toast): delay animation into next frame

- packages/core/scss/components/_forms.scss
GitHub Issue Number: #273 
Inputs no longer starts already invalid.
Only after submit, it takes the invalid css styles.
> fix(core/form-validation): form-validation invalid correction

- packages/core/src/components.d.ts
- packages/core/src/components/typography/test/ix-typography.spec.tsx
- packages/core/src/components/typography/types.ts
- packages/core/src/components/typography/typography.tsx
> feat(core/typography): add color property

- packages/core/component-doc.json
- packages/core/src/components/message-bar/message-bar.scss
- packages/core/src/components/message-bar/message-bar.tsx
- packages/core/src/components/message-bar/test/__snapshots__/message-bar.spec.tsx.snap
- packages/core/src/components/message-bar/test/message-bar.spec.tsx
> feat(core/message-bar): enable shadow dom

- packages/core/component-doc.json
- packages/core/src/components/tile/tile.scss
- packages/core/src/components/tile/tile.tsx
> feat(core/tile): enable shadow dom

- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/icon-button/icon-button.tsx
[IX-137]
- Added icon-button deprecated message for size 32 on icon-button
> fix(core/icon-button): deprecated size 32 

- packages/angular/src/components.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/tab-item/tab-item.tsx
- packages/core/src/components/tabs/tabs.tsx
- packages/core/src/components/tabs/test/tabs.ct.ts
- packages/vue/src/components.ts
GitHub Issue Number: #645 
- Add additional event to ix-tabs and ix-tab-item
> feat(core/tabs): add additional navigation events

- packages/angular/src/components.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/flip-tile-content/flip-tile-content.tsx
- packages/core/src/components/flip-tile/flip-tile.scss
- packages/core/src/components/flip-tile/flip-tile.tsx
- packages/core/src/components/flip-tile/test/flip-tile.ct.ts
- packages/vue/src/components.ts
> feat(core/flip-tile): migrate to shadow dom

- BREAKING_CHANGES.md
- packages/angular/src/components.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/select/select.tsx
GitHub Issue Number: 
Closes #280
> refactor(core/select): change itemSelectionChange event signature

- packages/angular/src/modal/modal.config.ts
- packages/angular/src/modal/modal.service.spec.ts
- packages/angular/src/modal/modal.service.ts
GitHub Issue Number: closes #700 
- The EmbeddedView created in the ModalService using the TemplateRef is now attached to ApplicationRef so it is included in the change detection.
- Improved typings of content on ModalConfig of @siemens/ix-angular
> fix(angular): fix change detection on modal when using a TemplateRef

- packages/angular-test-app/src/app/app-routing.module.ts
- packages/angular-test-app/src/app/app.module.ts
- packages/angular-test-app/src/preview-examples/select-ng-model.ts
- packages/angular/src/components.ts
- packages/angular/src/index.ts
- packages/angular/src/module.ts
- packages/angular/src/select-value-accessor.ts
- packages/angular/src/value-accessor.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/select/select.tsx
- packages/core/src/components/select/test/select.ct.ts
- packages/core/stencil.config.ts
- packages/documentation/docs/controls/select.md
- packages/vue/src/components.ts
GitHub Issue Number: closes #736 
- Added valueAccessorConfigs for `ix-select` to angular output target
- Change `selectedIndices` to `value` in order to work with Stencil's generated ValueAccessor. Backward compatibility was added. Deprecated `selectedIndices`.
- Change `itemSelectionChange` to `valueChange` (Backward  compatibility added). `valueChange` now emits a single value if `mode='single'` and an array if `mode='multiple'`. This is more close aligned with the default behavior of a native select element. Deprecated `itemSelectionChange`.
- Tested the generated angular component with `[ngModel]`.
- Tested the web component to make sure behavior did not changed in all …
> [IxSelect]: Support for Angular Forms

- packages/core/src/components/select/select.tsx
- packages/core/src/components/select/test/select.ct.ts
- Selection of added options in `<ix-select editable/>` does not work.
- Selecting a created option with `editable` works now with Shadow DOM.
- Modified the items getter to also retrieve `ix-select-item` inside the shadow DOM.
> fix(core/select): fix editable mode with shadow DOM

- packages/core/src/components/tree/tree.tsx
> fix(core/tree): add undefined check to disconnected callback

- packages/core/src/components/utils/application-layout/service.ts
- when using breakpoints inside the basic navigation, there might occur strange behavior when some breakpoints are not supported
- e.g ['sm', 'md'] -> on lg 'sm' would be used instead of md
- e.g ['md', 'lg'] -> on sm 'sm' would be used
- only supported breakpoints are evaluated
- lg has a different breakpoint logic
- if md is not available, sm will be used instead of md
> fix(core/basic-navigation): fixed behavior on missing breakpoints

- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/chip/chip.tsx
- packages/documentation/docs/controls/_chip_code.md
- packages/documentation/docs/controls/_chip_styleguide.md
- packages/documentation/docs/controls/chip.md
> docs: chip styleguide 

- packages/angular/src/components.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/date-picker/date-picker.tsx
- packages/core/src/components/datetime-picker/datetime-picker.tsx
- packages/core/src/components/time-picker/time-picker.tsx
- packages/documentation/docs/controls/date-picker.md
> docs(datepicker): add since tags

- packages/aggrid/scss/ix-aggrid.scss
Ag-grid allows selecting rows of a table by adding checkboxes to the start of a row. The actual `<input type="checkbox" />` element is only about half the size of the visible checkbox making it difficult to click the checkbox in order to select a row.
Example: https://ix.siemens.io/docs/grid/#usage
The size of the `<input type="checkbox" />` element now corresponds to the visible size of the checkbox.
Manually clicking the checkbox
Before:
After:
> fix: aggrid checkbox sizing

- packages/core/stencil.config.ts
When building on Windows, the relative paths are formatted in Windows style and getting escaped (e.g., \\src\\components\\action-card.tsx), potentially causing issues in the pipeline due to inconsistent path formats. To ensure seamless behavior, a small adaptation has been made to transform paths to Unix-style, even when building on Windows.
Tested on Windows 10 and Fedora 38.
All paths are getting formated in a unix style way
-
-
-
> fix(core/windows-doc-generation): fix for component-doc generation

- packages/react/src/internal-components.ts
- packages/vue/src/internal-components.ts
React and Vue have to define the internal components they are not part of the generation.
> fix(react|vue): define internal components

- packages/core/src/components/dropdown/dropdown-controller.ts
- packages/core/src/components/dropdown/test/dropdown-controller.spec.ts
Allow the typeguard to check undefined object.
> fix(core/dropdown): check against undefined access

- packages/core/src/components/menu/burger-menu.scss
- packages/core/src/components/menu/burger-menu.tsx
- packages/core/src/components/menu/test/menu.ct.ts
- Before the chevron button was flipped via rotation which caused the aria-label to be wrong while expanded
- Now the icon will get swapped instead and the aria label will get computed anew everytime the menu toggles
-
> fix(core/burger-menu): a11y expand state

- packages/core/src/components/dropdown/dropdown-controller.ts
- packages/core/src/components/dropdown/dropdown.tsx
- packages/core/src/components/menu-avatar-item/test/menu-avatar-item.ct.ts
GitHub Issue Number: Closes #1105 
If the ix-dropdown-item is hosted inside a wrapper like `ix-menu-avatar-item` it is necessary to provide the trigger indicator on the host level.
> fix(core/menu-avatar-item): use host for trigger target

- packages/angular/src/ix-icon.ts
GitHub Issue Number: Closes #1057
Add size property to angular proxy component
> fix(angular): icon size property missing in wrapper generation

- .changeset/silver-ads-flow.md
- packages/core/src/components/toggle/toggle.scss
When I change font-size with 14px for mobile view, ix-toggle is broken.
Actually problem is that rem unit has not been using for width and height.
please use rem unit instead of px. because it is relative unit .
GitHub Issue Number: #1111
- Px unit replaced with rem then it is responsive
-
> fix(toggle): fixed toggle circle with and height

- .changeset/sweet-yaks-appear.md
- packages/core/src/components/select-item/select-item.tsx
- packages/core/src/components/select/select.tsx
0 is currently not a valid value option for the ix-select-item.
GitHub Issue Number: xxx
0 is now a valid value option for the ix-select-item.
The test is skipped, since html only uses string values, which the value prop also will use in 3.0.
> fix(core/select-item): check by undefined not by value

- .changeset/short-bulldogs-repeat.md
- packages/core/src/components/tooltip/test/tooltip.ct.ts
- packages/core/src/components/tooltip/tooltip-controller.ts
- packages/core/src/components/tooltip/tooltip.tsx
- packages/core/src/components/utils/overlay.ts
IX-896
Prevent tooltip focusin event to call showTooltip, if a setTimeout call is already running.
> fix(core/tooltip): prevent focusin event call showTooltip

- .changeset/dry-roses-brake.md
- packages/angular-test-app/src/preview-examples/modal-by-template.ts
- packages/angular/src/modal/modal.service.spec.ts
- packages/angular/src/modal/modal.service.ts
- The modal can overflow (e.g very long text in the the modal content) because of the wrapper applied 
- Behavior has also been tested in react, but is only observerable in Angular
GitHub Issue Number:  Closes #1035, Closes #701, IX-861
- CSS Property applied
- Adjusted the wrapper of the template
-  Modal does not overflow anymore (test-case already created,  but does not emerge in stencil )
> fix(angular/modal): avoid overflow of modal content

- .changeset/tame-shrimps-press.md
- packages/core/src/components/menu/menu.tsx
Using slot for content results sometimes to empty tooltip within the menu, to avoid this use the label property.
> fix(core/menu): use label property to render internal menu items

- .changeset/kind-maps-approve.md
- packages/core/component-doc.json
- packages/core/src/components/workflow-step/workflow-step.tsx
GitHub Issue Number: closes #999, IX-882
Set icon name before component is loaded first time. 
> fix(core/workflow-step): load icon names before component is initialized

- .changeset/olive-seas-type.md
- .gitignore
- packages/core/package.json
- packages/core/stencil.config.ts
Cannot use IX via SSR
A new Hydration output is generated so that it can be used to hydrate the IX components on the server
- Please help with the changeset
- Should we add an extra doc information to the installation page regarding SSR?
> feat(core): added hydrate output target

- .changeset/great-files-tie.md
- packages/core/scss/mixins/_scrollbar.scss
- packages/core/src/components/menu/menu.scss
- packages/core/src/components/pagination/pagination.scss
- packages/core/src/components/tab-item/tab-item.scss
- Input, spefically the pagination has the increment / decrement buttons shown
- Default Scrollbar applied in Firefox
GitHub Issue Number: #N/A, [IX-1126], [IX-1127], [IX-1207]
Note: Viva Engage Firefox issue has also been adapted
- Increment / Decrement buttons are hidden
- Unfortunately Firefox does not offer that big of a support of scrollbar styling, so only available classes have been used (see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling)
- Note: There is a difference between the default Firefox Scrollbar in Windows 10 and Windows 11!
- No Tests, since we only test in Chrome
> fix(core/scrollbar): fix firefox appearance (scrollbar & input & tabs)

- .changeset/rare-numbers-double.md
- packages/vue/package.json
- packages/vue/rollup.config.mjs
- pnpm-lock.yaml
GitHub Issue Number: #1123 
- Remove commonjs from `@siemens/ix-vue`
> feat(vue): remove commonjs

- .changeset/twenty-hornets-sort.md
- packages/core/scss/components/form/_input.scss
- packages/core/src/components/menu-item/menu-item.scss
- packages/core/src/components/menu/menu.tsx
- The menu is always scrollable in FF
- The calculation to determine if scrolling is necessary, does not function correctly
- Default +/- buttons are visible at the input type=number
- Menu is only scrollable on overflow
- Default +/- buttons are hidden
> fix(core/menu): fix firefox overflow behavior and input styling

- .changeset/real-jokes-walk.md
- packages/angular/src/app-initialize.ts
- packages/core/.eslintignore
- packages/core/component-doc.json
- packages/documentation/static/code-runtime/html/src/main.js
- packages/html-test-app/src/main.js
- packages/html-test-app/src/preview-examples/init.js
- packages/vue/src/plugin.ts
- pnpm-lock.yaml
GitHub Issue Number: https://github.com/ionic-team/stencil/pull/5725
> build: remove internal polyfills

- .changeset/soft-pens-reply.md
- packages/core/component-doc.json
- packages/core/src/components/pagination/pagination.tsx
- Arrow buttons get disabled if count is either 0 or undefined
-
> fix(core/pagination): disable buttons if count is unset

- .changeset/ninety-ligers-invite.md
- packages/core/src/components/tooltip/tooltip.tsx
- When the reference element is scrolled out of view, the change detection is nevertheless triggered, which leads to performance issues
GitHub Issue Number: #N/A, [IX-1603]
- on referenceHidden the tooltip gets hidden and the cleanup function is called
Findings:
- When window not in focus -> hover / mouse leave does not work (check scope of ticket? -> was this meant?)
- Strange behavior in combination with angular devtools -> influence performance?
> fix(core/tooltip): cancel tooltip positioning when reference is not visible

- .changeset/breezy-hotels-tap.md
- packages/core/src/components/modal/modal.tsx
- packages/core/src/components/modal/test/modal.ct.ts
- modal closing fires 2 events
GitHub Issue Number: Closes #1149, [IX-985]
- removed onClose / onDismiss on dialog as this triggers the closing methods again
> fix(core/modal): fires 2 events on closing

- packages/angular-test-app/src/preview-examples/blind-header-actions.ts
When viewing the [blind example](https://ix.siemens.io/docs/controls/blind), the dropdown options in the angular documentation are missing.
Now the angular-test-app and therefore also the documentation is updated with dropdown options
> docs: add dropdown items to angular blind-header-actions example

- packages/angular/src/components.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/category-filter/category-filter.tsx
- packages/vue/src/components.ts
> refactor(core/category-filter): remove aria label

- packages/documentation/docs/controls/_date-input_code.mdx
- packages/documentation/docs/controls/_date-input_styleguide.mdx
- packages/documentation/docs/controls/date-input.mdx
- UX description for date input
> docs: date input ux description

- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/select/select.tsx
- packages/documentation/docs/controls/_date-input_styleguide.mdx
- packages/documentation/docs/controls/_number-input_styleguide.mdx
- packages/documentation/docs/controls/_select_styleguide.md
- packages/documentation/docs/controls/_textarea-field_styleguide.mdx
> Docs/formwwriting update/review

- packages/documentation/docs/guidelines/theme.md
As a follow up to #1523
Currently the documentation does not mention the import of bootstrap. So when splitting it up into ./core and the custom themes the styles are off
Idk if there is a reason why this wasnt mentioned in the documentation, but i added it in case its ok to add.
GitHub Issue Number: #1523
-
-
> Update Documentation to include 3rd Party libs

- .changeset/lovely-garlics-pretend.md
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/dropdown/dropdown-controller.ts
- packages/core/src/components/select-item/events.ts
- packages/core/src/components/select-item/select-item.tsx
- packages/core/src/components/select/select.tsx
Addition to #1548
- select in angular logs an error to the console when initializing the select-items in async 
- last element has always an undefined value
- angular seems to initialize components differently than react (possibly due to the vdom)
GitHub Issue Number: N/A, [IX-1918]
- before the selection is updated, it is checked if the value is  defined
- valueChange emited and selection updated
- updateSelection still needed when select properties change!
- removed "get dropdownItem()", method is never called - only appearance in select.tsx does not call this methods 
- only needed for the addItem, which is not a select-item (it is a dropdown-item)
- label / value changes only occur after the components has been initalised -> fewer events are thrown, also the slotChange takes care …
> fix(core/select): check if value is defined, before updating selection

- .changeset/funny-kiwis-run.md
- packages/core/src/components/menu/menu.tsx
A null pointer error appears when opening the menu.
- The error does not appear
> fix(menu): Menu component null pointer error

- packages/core/src/components/input/input.mixins.scss
- packages/storybook-docs/package.json
- packages/storybook-docs/src/stories/input.stories.ts
- pnpm-lock.yaml
Add a mask example as story to storybook
> chore(storybook): add maskito example

- .changeset/giant-melons-worry.md
- packages/angular/src/control-value-accessors/text-value-accessor.ts
the wrong selector was used. it was not possible to access any values via "formControlName" in case of ix-number-input. Reason: ix-number-field does not exist
- Values from ix-number-input are accessiable via formControlName
> fix: update selector in value-accessor for ix-number-input

- .changeset/silly-pandas-peel.md
- packages/core/src/components/message-bar/message-bar.scss
- packages/core/src/components/message-bar/message-bar.tsx
- packages/core/src/components/message-bar/test/message-bar.ct.ts
- Examples of DOM removal already done in the last PR
- Button interactions still possible
- d-none applied but not implemented
GitHub Issue Number: Closes #1608, [IX-2201]
- implemented d-none
- Buttons not reachable through mouse or keyboard interactions
- also NVDA screen reader was tried -> buttons are not interactable
> fix(core/message-bar): hide entire `ix-message-bar` and turn off user-interactions

- packages/documentation/docs/language/main-menu-functions.md
Writing guide shows copyright of Siemens with `AG`
The copyright info should be without AG.
> docs(ux-writing): copyright information of Siemens without `AG`

- .github/workflows/pr.yml
This pr ensures that the complete test suite is executed whenever Renovate creates new pull requests. This change is necessary because the default workflow configuration is optimized to run tests only for the modified packages.
> ci(renovate): run all tests for renovate prs

- .changeset/witty-geese-swim.md
- packages/angular/src/components.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/datetime-picker/datetime-picker.tsx
- packages/vue/src/components.ts
GitHub Issue Number: #1759
-
-
> feat(date-time-picker): add time label i18n

- .changeset/curly-berries-count.md
- .changeset/old-wasps-vanish.md
- .changeset/olive-ducks-applaud.md
- .changeset/pretty-fans-reply.md
- packages/angular/src/components.ts
- packages/angular/standalone/src/components.ts
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/checkbox-group/checkbox-group.tsx
- packages/core/src/components/checkbox-group/test/checkbox-group.ct.ts
- packages/core/src/components/checkbox/checkbox.tsx
- packages/core/src/components/input/input.fc.tsx
- packages/core/src/components/input/input.tsx
- packages/core/src/components/input/number-input.tsx
- packages/core/src/components/input/tests/validation.ct.ts
- packages/core/src/components/radio-group/radio-group.tsx
- packages/core/src/components/radio-group/test/radio-group.ct.ts
- packages/core/src/components/radio/radio.tsx
- packages/core/src/components/toggle/toggle.tsx
- packages/core/src/components/utils/input/index.ts
- packages/core/src/components/utils/input/validation.ts
- packages/react/src/components.server.ts
- packages/react/src/components.ts
- packages/storybook-docs/src/stories/checkbox-group.stories.ts
- packages/storybook-docs/src/stories/checkbox.stories.ts
- packages/storybook-docs/src/stories/input-number.stories.ts
- packages/storybook-docs/src/stories/input.stories.ts
- packages/storybook-docs/src/stories/radio-group.stories.ts
- packages/storybook-docs/src/stories/toggle.stories.ts
- packages/vue/src/components.ts
GitHub Issue Number: Fixes #1801 
- Avoid initial validation of required boolean components (ix-radio, ix-checkbox, ix-toggle)
- Handle group validation of radio and checkbox
- Show required indicator (*) for ix-radio-group and ix-checkbox-group
> fix(core): avoid initial validation of required boolean input types

- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/checkbox-group/checkbox-group.tsx
- packages/core/src/components/date-input/date-input.tsx
- packages/core/src/components/input/input.tsx
- packages/core/src/components/radio-group/radio-group.tsx
- packages/core/src/components/radio/radio.tsx
- packages/core/src/components/slider/slider.tsx
- packages/core/tsconfig.lib.json
- Enable `strict: true` inside tsconfig of `@siemens/ix`
> chore(core): enable strict tsconfig

- .changeset/sour-games-unite.md
- packages/core/src/components/modal/test/modal.ct.ts
- packages/core/src/components/utils/modal/message.ts
GitHub Issue Number: Fixes #1886
Util functions still used the legacy icon reference by string.
> fix(core/message): use icon imports within predefined messages

- .changeset/nine-baboons-own.md
- packages/core/src/components/chip/chip-mixin.scss
- packages/core/src/components/chip/chip.tsx
- packages/core/src/components/pill/pill.tsx
When icon is not set on ix-chip or ix-pill warnings are printed on the console.
GitHub Issue Number: Fixes #1885, Fixes #1879
- Instead of hiding the ix-icon element, it's not rendered if icon is not set on ix-pill and ix-chip
> fix(core): dont render ix-icon when icon is not set on ix-pill and ix-chip 

- .changeset/warm-walls-help.md
- packages/angular/standalone/src/internal-components.ts
- packages/react/src/internal-components.ts
- packages/vue/src/internal-components.ts
GitHub Issue Number: #2003 
Other components, such as IxIconButton, may internally use `<ix-icon>`, but if you never directly import/use IxIcon (e.g React), the underlying web component registration may never happen. This leads to <ix-icon> not being defined as a custom element, causing rendering issues when its dependent components attempt to use it.
https://github.com/siemens/ix/blob/6b9a8fc5922f936a96e3f09e8ea11e0720aa5383/packages/react/src/ix-icon.tsx#L22-L28
> fix: define ix-icons component as internal component

- packages/core/src/components/date-input/date-input.tsx
- packages/core/src/components/date-input/tests/date-input.ct.ts
- packages/core/src/components/time-input/test/time-input.ct.ts
- packages/core/src/components/time-input/time-input.tsx
- packages/core/src/components/time-picker/time-picker.tsx
- enter invalid date
- close dropdown
- reopen dropdown and select a time --> component breaks
- does not break anymore (keeps the previous valid time selected in the picker)
> fix(core/time-input): Invalid input of time-input breaks the component

- packages/core/src/components/time-picker/test/time-picker.ct.ts
- packages/core/src/components/time-picker/time-picker.tsx
Navigating the numbers in ix-time-picker currently uses arrow keys.
- Navigate between columns using tab
- Navigate inside columns using up/down arrow
- Losing focus inside a column realigns the seleted value
Jira: IX-2862
> feat(core/time-picker): Change keyboard navigation

- .changeset/metal-ants-hope.md
- packages/core/component-doc.json
- packages/core/src/components.d.ts
- packages/core/src/components/tree/tree.tsx
RefreshTreeOptions is currently not imported in components.d.ts after building.
RefreshTreeOptions is now correctly imported and no longer causes an error.
> fix(core/tree): Fix RefreshTreeOptions missing import after build

- .changeset/late-mugs-yell.md
- packages/core/src/components/tooltip/tooltip.scss
The ix-tooltips are not displayed correctly when using the Safari browser.
GitHub Issue Number: #2009
- The styling of the tooltip container height was fixed.
> fix(core/tooltip): Fix tooltip styling

- .changeset/healthy-knives-repeat.md
- packages/core/src/components/utils/test/theme-switcher.spec.ts
- packages/core/src/components/utils/theme-switcher.ts
The MutationObserver in the theme-switcher currently only checks for changes on the documentElement.
The MutationObserver now checks for both document body and documentElement
> fix(core/theme-switcher): Fix MutationObserver for document body

- .changeset/rich-walls-shave.md
- packages/angular/src/providers/toast/toast.service.ts
- packages/core/component-doc.json
- packages/core/src/components/toast/toast-utils.ts
- packages/documentation/scripts/typedoc-generator.ts
IX-2903
Currently descriptions for functions in angular services are not added to the documentation
- Now adds comments above functions in angular services as description to the documentation
- Add missing comments for toast
> feat(core/toast): Missing documentation

- .changeset/little-bananas-fail.md
- packages/core/src/components/modal/modal.scss
If the user has scrolled down the web page to trigger the modal, the modal dialog may be rendered outside the visible area of the viewport, making it inaccessible without manual scrolling.
GitHub Issue Number: #2083 
If the user has scrolled down the web page to trigger the modal, the modal dialog will be rendered in visible area of the viewport.
-
-
> fix(core/modal): Modal showing outside viewport when trigger button at bottom of the page
