siemens/ix

.github/workflows/actions/build/action.yml, .github/workflows/actions/install/action.yml, .github/workflows/actions/test/action.yml, .github/workflows/actions/visual-regression/action.yml, .github/workflows/build.yml, .github/workflows/pre-publish.yml, .github/workflows/publish.yml, .husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-push
=> ci: add github actions

packages/documentation/src/pages/index.tsx
Fix desciption text of landing page
=> docs(landing-page): fix description text

packages/documentation/docusaurus.config.js
Change baseUrl to "/" to fix loading error with ix.siemens.io domain
=> fix(documentation): change baseUrl to /

.github/workflows/actions/visual-regression/action.yml, .github/workflows/build.yml, .github/workflows/deploy-pages.yml, .github/workflows/pre-publish.yml, .github/workflows/publish.yml, CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/react-test-app/package.json, packages/react/package.json, scripts/common.js
Add GitHub actions to publish library
=> ci(workflow/publish): add publish workflow

.github/workflows/pre-publish.yml, .github/workflows/publish.yml
=> Release/1.0.0 beta.2

.npmrc, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/package.json, packages/react-test-app/package.json, packages/react/package.json, yarn.lock
Update @siemens/ix-icons to latest version 1.0.0
=> Update ix icons deps

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/react-test-app/package.json, packages/react/package.json
Add ix-brand-theme as optional peerDependency
=> chore: bump ix version to 1.0.0-beta.3

.github/workflows/pre-publish.yml, .github/workflows/publish.yml, CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/react-test-app/package.json, packages/react/package.json
bump ix version to 1.0.0-beta.5
=> Release/v1.0.0 beta.5

packages/documentation/docs/auto-generated/previews/web-component/modal.md, packages/documentation/docs/auto-generated/previews/web-component/toast-custom.md, packages/documentation/docs/auto-generated/previews/web-component/toast.md, packages/documentation/docs/getting-started-for-designers.md, packages/documentation/docs/getting-started.md, packages/documentation/src/components/SwitchTheme.tsx, packages/documentation/static/webcomponent-examples/modal.html, packages/documentation/static/webcomponent-examples/toast-custom.html, packages/documentation/static/webcomponent-examples/toast.html
=> fix review comments of documentation

README.md
The version displayed in the badge of the readme file did not match the version currently released (1.0.0).
- Running yarn test
- Manual test via local preview in IDE
=> fix(readme): changed the version to 1.0.0

packages/core/component-doc.json, packages/core/src/components/toast/test/cw-toast.spec.tsx, packages/core/src/components/toast/toast.tsx, packages/documentation/docs/auto-generated/ix-toast/props.md
Set default icon for toasts to info
=> fix(core/toast): set default icon to info

packages/angular-test-app/package.json, packages/angular-test-app/src/app/app-routing.module.ts, packages/angular-test-app/src/app/app.module.ts, packages/angular-test-app/src/preview-examples/workflow-vertical.ts, packages/angular-test-app/src/preview-examples/workflow.ts, packages/angular-test-app/src/styles.scss, packages/angular-test-app/tsconfig.json, packages/core/stencil.config.ts, packages/documentation/docs/auto-generated/previews/angular/workflow-vertical.md, packages/documentation/docs/auto-generated/previews/angular/workflow.md, packages/documentation/docs/auto-generated/previews/react/workflow-vertical.md, packages/documentation/docs/auto-generated/previews/react/workflow.md, packages/documentation/docs/auto-generated/previews/web-component/workflow.md, packages/documentation/docs/controls/workflow.md, packages/documentation/scripts/generate-api.mjs, packages/documentation/src/pages/index.tsx, packages/html-test-app/src/preview-examples/workflow.html, packages/react-test-app/src/main.tsx, packages/react-test-app/src/preview-examples/workflow-vertical.tsx, packages/react-test-app/src/preview-examples/workflow.tsx
- Add missing documentation for workflow
- Fix path in documentation generation script
- Add link to GitHub Discussions (Unfortunately not a separate commit)
=> create documentation page for workflow component alias stepper

packages/documentation/src/pages/index.module.scss
Implemented the mobile version for the 428 resolution
Tested locally
=> feat(documentation): mobile version

README.md
Fix a minor typo in the README
=> fix(docs): minor typo of dont

packages/documentation/docs/controls/grid/grid.md
Missing installation and import statement of ix-aggrid package
=> docs(aggrid): add installation instruction

packages/angular-test-app/src/app/app-routing.module.ts, packages/angular-test-app/src/app/app.module.ts, packages/angular-test-app/src/preview-examples/tabs-rounded.ts, packages/documentation/docs/auto-generated/previews/angular/tabs-rounded.md, packages/documentation/docs/auto-generated/previews/web-component/tabs-rounded.md, packages/html-test-app/src/preview-examples/tabs-rounded.html
Add missing rounded tabs example
Nothing to test here
=> feat(angular-test-app): add rounded tabs example

scripts/lint-build.sh
Lint of build detect invalid build during documentation deployment.
=> ci(lint-build): lint only package changes inside packages

packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/date-picker/date-picker.tsx, packages/core/src/components/date-picker/readme.md, packages/core/src/components/datetime-picker/datetime-picker.tsx, packages/core/src/components/my-component/my-component.tsx, packages/core/src/components/time-picker/readme.md, packages/core/src/components/time-picker/time-picker.tsx
Datepicker api expose typing of luxon which is not suitable
=> fix(core/datepicker): remove luxon typing from component interface

README.md
=> docs(readme.md): update copyright year

packages/core/src/components/map-navigation-overlay/map-navigation-overlay.tsx
=> fix(core/map-nav-overlay): prevent overlay from blocking DOM when hidden

packages/core/src/components/select/select.tsx, packages/core/src/components/select/test/cw-select.spec.tsx
Prevent string to be spread by '...' operator
=> fix(core/select): prevent string to be spread by '...' operator

packages/angular/src/modal/modal.service.ts
Angular modal service did not pass all config objects to core modal function
Discussed in: https://github.com/siemens/ix/discussions/178
- Pass config object to function by spread operator
=> fix(angular/modal-service): pass config object to modal function

packages/angular-test-app/src/preview-examples/dropdown.ts, packages/angular/src/dropdown/trigger.directive.ts, packages/angular/src/index.ts, packages/angular/src/module.ts
GitHub Issue Number: #154 
- Add angular directive to get nativeElement of template variable
=> feat(angular/dropdown): add trigger directive

README.md, packages/documentation/docs/getting-started-for-designers.md, packages/documentation/docs/getting-started.md, packages/documentation/docusaurus.config.js, packages/documentation/src/pages/index.tsx
GitHub Issue Number: 221
-
-
-
=> docs(landing-page): update text content

packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/chip/chip.tsx, packages/core/src/components/chip/readme.md, packages/documentation/docs/controls/group.md
GitHub Issue Number: #225
-
-
-
=> docs(group): reference correct angular example

packages/aggrid/scss/ix-aggrid.scss, packages/core/component-doc.json, packages/core/scss/components/_checkboxes.scss, packages/core/scss/components/_radiobuttons.scss, packages/core/scss/theme/classic-dark/_variables.scss, packages/core/scss/theme/classic-light/_variables.scss, packages/core/src/components/group-item/group-item.scss, packages/core/src/components/group/group.scss, packages/core/src/components/my-component/my-component.tsx, packages/html-test-app/src/preview-examples/aggrid.html
GitHub Issue Number: #233 
- Hide radiobutton and checkbox without `pointer-events: none`
- Remove default checkbox styling in aggrid theme
=> fix(core/checkbox, core/radiobutton): hide native intput

packages/documentation/src/theme/Loader.tsx, packages/documentation/src/theme/Root.tsx, packages/documentation/src/theme/SiteMetadata/index.js
Docusaurus use SSR to generate docs, this cause sometimes a problems during loading of the Web Components
- Load Web Components in Root file only in Browser.
=> docs: bootstrap webcomponents in root file

packages/angular-test-app/src/preview-examples/button-ghost.ts, packages/angular-test-app/src/preview-examples/button-grey-ghost.ts, packages/angular-test-app/src/preview-examples/button-secondary.ts, packages/angular-test-app/src/preview-examples/button-selected.ts, packages/angular-test-app/src/preview-examples/buttons.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/button/button.tsx, packages/core/src/components/button/readme.md, packages/core/src/components/map-navigation-overlay/map-navigation-overlay.tsx, packages/html-test-app/src/preview-examples/button-ghost.html, packages/html-test-app/src/preview-examples/button-grey-ghost.html, packages/html-test-app/src/preview-examples/button-selected.html, packages/react-test-app/src/preview-examples/button-ghost.tsx, packages/react-test-app/src/preview-examples/button-grey-ghost.tsx, packages/react-test-app/src/preview-examples/button-selected.tsx, packages/react-test-app/src/preview-examples/buttons.tsx
=> docs(buttons): update examples and documentation

packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/tree/tree.tsx, packages/documentation/docs/controls/tree.md
=> docs(tree): add tree api to docs and fix jsdocs typo

packages/aggrid/scss/ix-aggrid.scss
- Remove clip and clip-path from `ag` related inputs, because click listener of aggrid subscribed for direct `<input/>` clicks.
=> fix(aggrid): remove clip from ag-radiobutton

packages/core/src/components/icon-button/icon-button.scss, packages/core/src/components/icon-button/icon-button.tsx, packages/core/src/components/icon-button/test/icon-button.spec.ts
- set `pointer-events: none` to host container.
=> fix(core/icon-button): prevent events during disable state

packages/core/src/components/modal/modal.scss
=> fix(core/modal): set max-height

packages/core/src/components/menu/menu.scss
=> fix(core/menu): update overlay animation

packages/core/src/components/button/button.scss, packages/core/src/components/button/button.tsx, packages/core/src/components/button/test/button.spec.tsx
GitHub Issue Number: #263 
Disable state of the button was handled via attribute property.
- Migrate from attribute selector to class selector
Add unit test case
=> fix(core/button): apply correct disable state

packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/select-item/select-item.tsx, packages/documentation/scripts/generate-api.ts, packages/documentation/scripts/utils.ts
Table `|` character was not escaped during rendering of markdown, which cause a break of the table.
- Escape all special markdown characters
=> docs(generate-api): escape markdown

packages/html-test-app/src/preview-examples/input-disabled.html, packages/html-test-app/src/preview-examples/input-readonly.html, packages/html-test-app/src/preview-examples/input-with-icon.html, packages/html-test-app/src/preview-examples/input.html
=> docs(example/input): prevent site reload

packages/documentation/docs/theming/theme.md, packages/documentation/package.json, packages/documentation/scripts/copy-webcomponents.ts, packages/documentation/scripts/generate-api.ts, yarn.lock
Delete autogenerated content before generate new content
=> docs(generate-api): rimraf auto-generated content

yarn.lock
- Update yarn.lock with latest @siemens/ix-icons version.
=> chore: update ix-icons to latest version

packages/documentation/docs/installation/javascript.md, packages/documentation/src/components/Playground/index.tsx, packages/documentation/static/code-runtime/angular/package.json, packages/documentation/static/code-runtime/html/package.json, packages/documentation/static/code-runtime/react/package.json
- improve javascript installation gruide
- update package.json of stackblitz runtimes
=> docs(installation/javascript): improve installation guide

packages/core/component-doc.json, packages/core/src/components/select-item/events.ts, packages/core/src/components/select-item/select-item.tsx, packages/core/src/components/select/select.tsx
- Replace MutationObserver with DOM Events.
=> fix(core/select): replace mutation observer with dom events

packages/core/component-doc.json, packages/core/src/components/dropdown-button/dropdown-button.tsx, packages/documentation/docs/controls/dropdown-button.md, packages/documentation/scripts/docs-tags.ts, packages/documentation/scripts/generate-api.ts, packages/documentation/scripts/renderer/api-renderer.ts, packages/documentation/scripts/utils.ts, packages/documentation/src/css/api-table.css, packages/documentation/src/css/custom.css
- Generate markdown files for component overview (jsdoc) and tags (jsdoc)
=> docs(generate-api): add since tag renderer on component level

packages/angular-test-app/src/preview-examples/split-button-icons.ts, packages/angular-test-app/src/preview-examples/split-button.ts, packages/documentation/docs/controls/split-button.md, packages/html-test-app/src/preview-examples/split-button-icons.html, packages/html-test-app/src/preview-examples/split-button.html, packages/react-test-app/src/preview-examples/split-button-icons.tsx, packages/react-test-app/src/preview-examples/split-button.tsx
=> docs(split-button): fix api and icon

packages/core/src/components/utils/theme-switcher.ts
There is a typo in "MutationObserver" in the theme-switcher why the check is always false
The following warning appears on all browsers
The if checks for the correct name and the MutationObserver will be used
=> fix(core/theme): correct typo for MutationObserver

packages/core/component-doc.json, packages/core/scss/components/_buttons.scss, packages/core/src/components.d.ts, packages/core/src/components/button/button.scss, packages/core/src/components/button/button.tsx, packages/core/src/components/button/test/button.e2e.ts, packages/core/src/components/button/test/button.spec.tsx, packages/core/src/components/dropdown-button/dropdown-button.scss, packages/core/src/components/dropdown-button/dropdown-button.tsx, packages/core/src/components/icon-button/icon-button.scss, packages/core/src/components/icon-button/icon-button.tsx
=> Revert "fix(core/button): remove wrapper level"

packages/documentation/docs/design-kit/design-kit.md
=> docs(design-kit): figma siemens section

packages/core/src/components/tree-item/tree-item.tsx
=> fix(core/tree-item): allow child elements to receive pointer events

packages/documentation/docs/controls/_toast/angular/toast-config.md, packages/documentation/docs/controls/_toast/angular/toast-service.html.md, packages/documentation/docs/controls/_toast/javascript/toast-config.md, packages/documentation/docs/controls/_toast/react/toast-config.md, packages/documentation/docs/controls/toast.md
=> docs(toast): add framework specific apis

packages/aggrid/scss/ix-aggrid.scss
=> fix(aggrid): convert px to rem

packages/core/component-doc.json, packages/core/src/components/menu-item/menu-item.scss, packages/core/src/components/menu-item/menu-item.tsx, packages/core/src/components/menu/menu.tsx
Use scope for component encapsulation to avoid broken slot behavior.
=> fix(core/menu): use scoped context in menu item

packages/documentation/docs/controls/_toast/javascript/toast-config.md, packages/documentation/docs/controls/toast.md
=> docs(core/toast): formatting

packages/core/src/components/tree/tree.tsx
=> fix(core/tree): set toggle listener when has children changes

packages/core/scss/components/_dropdown.scss
Remove button overwrite of button component
=> fix(core/dropdown): remove button overwrite

packages/core/src/components/dropdown-item/dropdown-item.tsx
GitHub Issue Number: #442 
- Added button type to dropdown-item to stop form using button as submit type.
=> fix(core/select): stop form trigger

yarn.lock
=> chore: update yarn.lock to latest ix-icons version

packages/documentation/docs/installation/javascript.md, packages/documentation/docs/installation/security.md, packages/documentation/docs/installation/vue.md
=> docs(security): add securty page with csp section

packages/core/src/components/modal-container/modal-container.tsx, packages/core/src/components/modal-container/test/modal-container.spec.tsx, packages/core/src/components/modal/modal.tsx, packages/core/src/components/modal/test/__snapshots__/modal.spec.tsx.snap, packages/react/src/modal/index.ts, packages/react/src/modal/modal.tsx
- Prevent event from bubble upwards.
- Change some part of the react wrapper to reduce `div` nesting
=> fix(core/modal): close only target modal

packages/core/src/components/toggle/toggle.scss
Remove `[disabled]` selector from styles file, because host component handle disabled state by a host class.
=> fix(core/toggle): remove attribute selector for disable state

package.json, packages/angular-test-app/package.json, packages/documentation/package.json, packages/eslint-config/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/vue-test-app/package.json
=> chore: add basic license to private modules

packages/aggrid/package.json, packages/core/component-doc.json, packages/core/package.json, yarn.lock
=> chore: update to @stencil/core 3.2.1

packages/angular-test-app/angular.json
Remove angular cli caching from `angular-test-app` to prevent unwanted compilation errors, after re-compile core.
=> chore(angular-test-app): disable angular cli cache

packages/core/component-doc.json, packages/core/src/components/blind/blind.scss, packages/core/src/components/blind/blind.tsx, packages/core/src/tests/blind/blind.e2e.ts
=> feat(core/bind): enable shadowDOM

packages/core/src/components/toast/toast.scss, packages/core/src/components/toast/toast.tsx
GitHub Issue Number: #455 
- When hovered, timer stops
- Stopping hover makes timer resume at the exact time where it stopped.
=> fix(core/toast): timer on hover

packages/documentation/src/pages/index.module.scss
Current homepage buttons and chevron-down have underline on hover.
- On hover no longer has underline.
=> fix(docs/homepage): button and arrow no text-decoration

packages/core/component-doc.json, packages/core/src/components/spinner/spinner.scss, packages/core/src/components/spinner/spinner.tsx
=> feat(core/spinner): enable shadow dom

packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/map-navigation/map-navigation.tsx
GitHub Issue Number: closing #531
=> feat(core/map-navigation): expose method to change visibility of sidebar

packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json, yarn.lock
=> chore: update to ix-icons 1.1.0

packages/angular-test-app/src/preview-examples/tooltip.html, packages/core/src/index.html, packages/html-test-app/src/preview-examples/tooltip.html, packages/react-test-app/src/preview-examples/tooltip.tsx, packages/vue-test-app/src/preview-examples/tooltip.vue
GitHub Issue Number: closes #483 
User said that example was not clear how it worked with the prop "for".
- Updated the example. Now two buttons with hover exist, one with simple selector and one with custom selector.
=> docs(tooltip): make example more common

packages/documentation/docs/migration/core-ui.md
Remove direct documentation link
=> docs(migration): remove direct repository link

yarn.lock
=> chore: update @siemens/ix-icons to 1.1.1

packages/core/component-doc.json, packages/core/scss/components/_forms.scss, packages/core/src/components/date-picker/date-picker.scss, packages/core/src/components/date-picker/date-picker.tsx, packages/core/src/components/date-time-card/date-time-card.scss, packages/core/src/components/date-time-card/date-time-card.tsx, packages/core/src/components/datetime-picker/datetime-picker.scss, packages/core/src/components/datetime-picker/datetime-picker.tsx, packages/core/src/components/time-picker/time-picker.scss, packages/core/src/components/time-picker/time-picker.tsx
=> feat(core/datetime-picker): enable shadow dom

packages/documentation/docs/introduction.md, packages/documentation/docs/team.md
=> docs(introduction): update intro page

.github/ISSUE_TEMPLATE/config.yml, README.md
Switch to Siemens Community Forum
=> docs(community): add community links

packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/dropdown-button/dropdown-button.tsx
=> fix(core/dropdown-button): deprecate unused property active

packages/core/component-doc.json, packages/core/scss/mixins/_hover.scss, packages/core/src/components/filter-chip/filter-chip.scss, packages/core/src/components/filter-chip/filter-chip.tsx
=> feat(core/filter-chip): enable shadow dom

packages/documentation/src/css/custom.css, packages/html-test-app/src/preview-examples/theme-switcher.html
=> docs(theme): underline brand theme link

packages/documentation/scripts/generate-api.ts
Remove copyright header for online examples ignore number of new lines
=> build(docs): ignore new lines of copyright header replacement

BREAKING_CHANGES.md, packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/button/button.scss, packages/core/src/components/split-button-item/split-button-item.css, packages/core/src/components/split-button-item/split-button-item.tsx, packages/core/src/components/split-button/split-button.scss, packages/core/src/components/split-button/split-button.tsx, packages/core/src/tests/split-button/split-button.e2e.ts, packages/vue/src/components.ts
=> feat(core/split-button): migrate to shadow DOM

packages/core/src/components/input-group/input-group.scss
GitHub Issue Number: closes #609 
- Changed start slot height to the same height as the input
=> fix(core/input): input start slot height

packages/documentation/docs/controls/_toast/angular/toast-service.html.md
- Fixed a typo in the angular controls section for ToastConfig
-
-
=> docs(angular): fix typo in toastconfig

packages/angular-test-app/src/preview-examples/aggrid.ts, packages/documentation/docs/controls/charts/charts.md, packages/documentation/docs/grid/grid.md, packages/documentation/src/pages/index.tsx, packages/html-test-app/src/preview-examples/aggrid.html, packages/react-test-app/src/preview-examples/aggrid.tsx, packages/vue-test-app/src/preview-examples/aggrid.vue
=> docs(ag-grid|echarts): add license information

packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/select/select.tsx, packages/vue/src/components.ts
GitHub Issue Number: closes #572 
- Added input event to Select component
=> feat(core/select): input event

.github/workflows/deploy-pages-daily.yml
Always have a uptodate version of the development documentation. (based on current main)
=> ci(action/pages): deploy dev instance daily

packages/documentation/docs/language/frequent-app-functions.md
=> docs: remove unwanted bullet point

packages/core/component-doc.json, packages/core/src/components/validation-tooltip/validation-tooltip.tsx
=> feat(core/validation-tooltip): migrate to shadow dom

packages/core/component-doc.json, packages/core/src/components/tree-item/tree-item.scss, packages/core/src/components/tree-item/tree-item.tsx, packages/core/src/components/tree/test/tree.ct.ts, packages/core/src/components/tree/tree.tsx
- Migrate to shadow dom
- Fix issue regarding update of padding
=> feat(core/tree): migrate to shadow dom

packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts
=> test(core/basic-navigation): add checks to prevent flaky tests

packages/react-test-app/src/preview-examples/modal.tsx
[In the beta documentation for the upcoming 2.0.0 release](https://ix.siemens.io/version-dev/docs/controls/modal), the example code for the modal shows a different usage for [react](https://ix.siemens.io/version-dev/docs/controls/modal#react) compared to [angular](https://ix.siemens.io/version-dev/docs/controls/modal#angular)/[vue](https://ix.siemens.io/version-dev/docs/controls/modal#vue)/[javascript](https://ix.siemens.io/version-dev/docs/controls/modal#javascript).
The react example uses classes to define the modal's header, content & footer while the examples for the other frameworks uses components.
- Correct styling of elements in the react …
=> docs(modal): update react usage of modal header, content & footer

packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/package.json, packages/core/src/components.d.ts, packages/core/src/components/dropdown-button/dropdown-button.scss, packages/core/src/components/dropdown-button/dropdown-button.tsx, packages/core/src/components/dropdown/dropdown.tsx, packages/documentation/src/components/SwitchTheme.tsx, packages/vue/src/components.ts, yarn.lock
=> fix(core/dropdownbutton): dropdown alignment

packages/core/src/components/card-accordion/card-accordion.scss
GitHub Issue Number: Closes #621
=> fix(core/pushcard): use std-text as default color

packages/core/src/components/blind/blind.tsx
GitHub Issue Number: Closes #519
Remove `<slot></slot>` when collapsed
=> fix(core/blind): remove blind content after collapse changed

packages/core/src/components/split-button-item/split-button-item.tsx, packages/core/src/components/split-button/split-button.tsx
GitHub Issue Number: Closes #708
=> fix(core/split-button): prevent inner event to bubble up

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs_bug_report.yml
=> chore(github): require code snippets for bug reports

packages/documentation/docusaurus.config.js, packages/documentation/scripts/generate-api.ts, packages/figma-plugin/figma.js, packages/figma-plugin/index.js
=> docs(figma): append base url to each image resource

packages/documentation/docs/controls/_breadcrumb_styleguide.md
checked and made changes. Should be checked by Katrin, final discussion in our weekly meeting then a final merge by Daniel.
-
-
-
=> docs(breakcrumb): gramma

packages/documentation/docs/controls/_breadcrumb_styleguide.md
- Update some grammer
- Fix typos
=> docs(breakcrumb): gramma (#749)

packages/angular-test-app/src/preview-examples/select-editable.ts, packages/angular-test-app/src/preview-examples/select-multiple.ts, packages/angular-test-app/src/preview-examples/select.ts, packages/angular-test-app/src/preview-examples/theme-switcher.html, packages/core/src/components/pagination/pagination.tsx, packages/core/src/components/select/test/select.ct.ts, packages/core/src/tests/select/allow-clear/index.html, packages/core/src/tests/select/autoplacement/index.html, packages/core/src/tests/select/basic/index.html, packages/core/src/tests/select/editable/index.html, packages/core/src/tests/select/list-header-hide/index.html, packages/core/src/tests/select/mode-multiple-overflow/index.html, packages/core/src/tests/select/mode-multiple/index.html, packages/core/src/tests/select/overflow/index.html, packages/core/src/tests/select/select.e2e.ts, packages/html-test-app/src/preview-examples/select-editable.html, packages/html-test-app/src/preview-examples/select-multiple.html, packages/html-test-app/src/preview-examples/select.html, packages/html-test-app/src/preview-examples/theme-switcher.html, packages/react-test-app/src/preview-examples/select-editable.tsx, packages/react-test-app/src/preview-examples/select-multiple.tsx, packages/react-test-app/src/preview-examples/select.tsx, packages/react-test-app/src/preview-examples/theme-switcher.tsx, packages/vue-test-app/src/preview-examples/select-editable.vue, packages/vue-test-app/src/preview-examples/select-multiple.vue, packages/vue-test-app/src/preview-examples/select.vue
=> docs(select): remove deprecated props/events

packages/core/src/components/button/button-mixin.scss
GitHub Issue Number: 
part of #711
- define correct button icon color for custom svg icons.
```
@siemens/ix-icons@beta.1 needed to test (not released yet)
```
=> fix(core): overwrite custom icon coloring

packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/core/src/components/breadcrumb-item/breadcrumb-item.scss, packages/core/src/components/icon-button/test/icon-button.ct.ts, packages/core/src/tests/split-button/split-button.e2e.ts, packages/documentation/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json, packages/vue/src/components.ts, yarn.lock
=> chore: update to ix-icons 1.2.0

BREAKING_CHANGES.md, packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/chip/chip.tsx, packages/core/src/components/dropdown-button/dropdown-button.tsx, packages/core/src/components/event-list-item/event-list-item.tsx, packages/core/src/components/menu-item/menu-item.tsx, packages/vue/src/components.ts
=> chore(core): remove deprecated props/events

packages/angular-test-app/src/app/app-routing.module.ts, packages/angular-test-app/src/app/app.module.ts, packages/angular-test-app/src/preview-examples/toggle-ng-model.ts, packages/angular/src/boolean-value-accessor.ts, packages/angular/src/index.ts, packages/angular/src/module.ts, packages/core/stencil.config.ts, packages/documentation/docs/controls/toggle.md
GitHub Issue Number: closes #742 
- Added valueAccesorConfig in angular output target for `ix-toggle` 
Tested the component with `[ngModel]`.
=> feat(core/toggle): support for angular forms

packages/documentation/docs/icon-library/_category_.json, packages/documentation/docs/icon-library/_icon_code.md, packages/documentation/docs/icon-library/_icon_styleguide.md, packages/documentation/docs/icon-library/icons.md
=> docs(icons): add style guide

packages/angular-test-app/src/preview-examples/dropdown-submenu.ts, packages/core/src/components/dropdown/dropdown.tsx, packages/core/src/components/dropdown/test/dropdown.ct.ts, packages/core/src/components/pagination/test/pagination.ct.ts, packages/core/src/components/select/select.tsx, packages/core/src/components/utils/shadow-dom.ts, packages/html-test-app/src/preview-examples/dropdown-submenu.html, packages/react-test-app/src/preview-examples/dropdown-submenu.tsx
=> fix(core/dropdown): remove shadow-dom workaround

packages/core/src/components/menu/menu.tsx, packages/core/src/components/menu/test/menu.ct.ts
GitHub Issue Number: closes #779 
- Added missing event to bottom slot
=> fix(navigation-menu): bottom slot click event

packages/angular-test-app/src/preview-examples/button-text-icon.ts, packages/html-test-app/src/preview-examples/button-text-icon.html, packages/react-test-app/src/preview-examples/button-text-icon.tsx, packages/vue-test-app/src/preview-examples/button-text-icon.vue
=> docs(buttons): use icon property to display icon

packages/documentation/docs/design-kit/design-kit.md, packages/documentation/docs/migration/2_0_0/index.md, packages/documentation/sidebars.js
=> docs: apply review comments

packages/core/src/components/modal/modal.tsx
Move showModal into next tick to be sure all shadow elements are rendered
=> fix(core/modal): skip tick during vdom rendering

packages/core/src/components/dropdown/dropdown.tsx, packages/core/src/components/dropdown/test/dropdown.ct.ts
- Trying to open a nested dropdown disposes the parent dropdown
- Can now open the nested dropdown
Added test case
=> fix(core/drodown): nested dropdown closes parent dropdown

packages/core/src/components/button/button-mixin.scss, packages/core/src/components/button/test/button.ct.ts
GitHub Issue Number: Closes #800
=> fix(core/button): prevent native events to be dispatched

packages/react/src/tree/tree.tsx
GitHub Issue Number: Closes #792
=> fix(react/tree): load ix-tree web component on initialize react lib

packages/core/src/components/input-group/input-group.tsx, packages/core/src/components/input-group/tests/input-group.ct.ts
GitHub Issue Number: Closes #801
=> fix(core/input-group): detect inital value padding

packages/core/src/components/breadcrumb-item/breadcrumb-item.tsx, packages/core/src/components/breadcrumb/breadcrumb.tsx, packages/core/src/components/utils/a11y.ts
GitHub Issue Number: Closes #809
=> fix(core/breadcrumb): check if overflow button is existing in DOM

packages/core/src/components/drawer/drawer.scss
GitHub Issue Number: Closes #814
=> fix(core/drawer): add missing host class selector

packages/core/scss/components/_checkboxes.scss, packages/core/scss/components/_radiobuttons.scss
GitHub Issue Number: Closes #808
=> fix(core/checkbox, core/radiobutton): remove min-height

packages/core/src/components/button/base-button.tsx, packages/core/src/components/button/button-mixin.scss
GitHub Issue Number: Closes #795 
- Prevent interaction with ix-icon component
=> fix(core/button): prevent interaction of ix-icon

packages/documentation/docs/installation/blazor.md
=> docs(blazor): upate info box

packages/core/component-doc.json, packages/core/src/components/dropdown/dropdown.tsx, packages/core/src/components/select/select.tsx, packages/core/src/components/slider/slider.tsx, packages/core/src/components/tabs/tabs.tsx, packages/core/src/components/utils/listener.ts, packages/core/src/components/utils/requestAnimationFrame.ts
GitHub Issue Number: Closes #846 Closes #862
- Request animation frame of zone, if the zone is present around the component.
- add global eventl istener only if event is necessary
Tested manual with Angular Dev Tools for Chrome in combination with the profiler tab.
=> fix(core): request animation depending on zonejs; reduce global events

packages/aggrid/gulpfile.ts, packages/aggrid/tests/basic.html, packages/aggrid/tests/pagination.html, yarn.lock
=> build(aggrid): include parent node_modules

packages/documentation/src/pages/index.module.scss
=> docs: reduce image size

packages/angular-test-app/src/preview-examples/button-secondary.ts
=> fix(core/button): documentation fix

packages/core/src/components/modal-header/modal-header.tsx
- ix-modal logs an error in the browser console if not used inside a <ix-modal>
- this appears on an unit test and also on the normal usage
GitHub Issue Number: 882
- condition to check whether it is used inside or outside an <ix-modal>
=> fix(core/modal-header): fix

packages/core/src/components/event-list-item/event-list-item.scss, packages/core/src/tests/event-list/chevron/index.html
=> fix(core/event-list-item): fix right padding

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.0.4-beta.0

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.0.4

packages/documentation/docs/roadmap.md, packages/documentation/sidebars.js
=> docs: roadmap

packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/basic-navigation/basic-navigation.tsx
=> doc(core/basic-navigation): documentation fix

packages/core/src/components/menu-item/menu-item.scss
=> fix(core/menu-item): suppress icon tooltip

packages/core/src/components/menu/burger-menu.scss
GitHub Issue Number: #936
- The cursor is now a pointer
Manually checked the cursor appearance in different scenarios.
no
=> fix(core/burger-menu): cursor appearance

packages/core/src/components/category-filter/category-filter.tsx, packages/core/src/components/select/select.tsx
GitHub Issue Number: #979
-
-
-
=> fix(core/select|category-filter): disable native autocomplete

packages/documentation/static/code-runtime/react/index.tsx
Resolved an issue associated with a segment of the React preview example's code runtime.
GitHub Issue Number: [983](https://github.com/siemens/ix/issues/983)
The modal preview example works as intended without throwing an error. This was achieved by adding IxApplicationContext to the `index.tsx` file of the React preview example's code runtime.
Conducted a manual test to verify the new behavior in relation to the modal preview example.
Closes #983
=> docs: add IxApplicationContext to React code runtime's index.tsx

packages/documentation/docs/controls/dropdown.md
• Identified the incorrect placement of JavaScript and HTML code
• Moved the JavaScript code to the correct location
• Moved the HTML code to the correct location
• Verified that the code is now correctly placed
• Issue Number is #975
=> Issue rectified - The positions of html and ts code in documentation has been corrected

packages/documentation/docusaurus.config.js
the link in the footer says Siemens Developer Portal
The link in the footer says [Siemens Xcelerator Developer Portal](https://developer.siemens.com) (the new name for the developer portal)
=> chore: xcelerator naming

.github/workflows/deploy-pages-daily.yml, .github/workflows/deploy-pages.yml
Installation of ix-brand-theme via npm in combination of an previous yarn installation breaks the dependencies. Tar file is now downloaded directly via shell command. Does not effect any dependency management, because theme file is only used with npm `fs` commands on filesystem not based on node_modules.
Copied both job commands because only intermediate step until pr #931 is merged.
Result: https://ix.siemens.io/version-dev/
=> ci(deployment): replace theme download method

packages/core/src/components/toast/toast-container.tsx
GitHub Issue Number: [1021](https://github.com/siemens/ix/issues/1021)
- Fixed toast message initial undefined error.
- Make this statement sync
-
=> fix(toast): fixed initial async undefined error

packages/core/component-doc.json, packages/core/package.json, packages/core/scss/_z-index.scss, packages/core/src/components.d.ts, packages/core/src/components/application-header/application-header.tsx, packages/core/src/components/dropdown-item/dropdown-item.tsx, packages/core/src/components/dropdown/dropdown-controller.ts, packages/core/src/components/dropdown/dropdown.tsx, packages/core/src/components/dropdown/test/dropdown.ct.ts, packages/core/src/components/menu-avatar-item/menu-avatar-item.tsx, packages/core/src/components/playground/playground.tsx, packages/core/src/components/split-button-item/split-button-item.tsx, packages/core/src/components/utils/internal/component.ts, packages/core/src/components/utils/internal/index.ts, packages/core/src/components/utils/make-ref.ts, packages/vue/src/components.ts, yarn.lock
GitHub Issue Number: Closes #895
All internal dropdown-item wrapper components have to implement the `DropdownItemWrapper` interface. This ensures that the features like sub menu icon can be activated.
https://github.com/siemens/ix/pull/919 will be closes because of a stale branch
=> fix(core/dropdown): check submenu item by interface

packages/core/scss/components/_radiobuttons.scss
GitHub Issue Number: #1045 1045
-
-
-
=> fix(core/radio-button): fix alignment of checked indicator

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.1.0-beta.1

packages/documentation/docs/controls/application-frame/_application-menu_styleguide.md
- add description of icon usage in second level items
- add example image with icons in second level
- remove "iX" in text
=> docs(app frame): update guidelines

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.1.0-beta.2

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.1.0-beta.3

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.1.0

packages/core/src/components/modal/modal.tsx
The modal is closing when focus some input element and press 'space'
GitHub Issue Number: #1077 
The reason was that clickoutSide is triggered when press the space,
I checked that if the event is pointer event (click or touch) or not
-
-
-
=> fix(core/modal): fixed closing modal issue when press space or enter

packages/core/src/components/modal/modal.tsx, packages/core/src/components/modal/test/modal.ct.ts, packages/core/src/components/utils/modal/modal.ts
Followup test cases for #1080 
=> test(core/modal): backdrop click

packages/angular-test-app/src/preview-examples/tooltip.html, packages/core/component-doc.json, packages/core/package.json, packages/core/src/components/tooltip/test/tooltip.ct.ts, packages/core/src/components/tooltip/tooltip.tsx, packages/documentation/docs/controls/tooltip.md, packages/html-test-app/src/preview-examples/tooltip.html, packages/react-test-app/src/App.tsx, packages/react-test-app/src/preview-examples/tooltip.tsx, packages/vue-test-app/src/preview-examples/tooltip.vue, yarn.lock
GitHub Issue Number: Closes #1114
Remove direct property access within rendering function.
=> fix(core/tooltip): remove direct constructor access

packages/core/src/components/menu-avatar-item/menu-avatar-item.scss
=> fix(core/menu-avatar-item): use correct theme color

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/controls/modal.md, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.1.1

packages/core/src/components/dropdown/dropdown.tsx
=> fix(core/dropdown): add null check

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.1.2-beta.0

CHANGELOG.md, package.json, packages/aggrid/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docs/installation/CHANGELOG.md, packages/documentation/package.json, packages/echarts/package.json, packages/html-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/vue-test-app/package.json, packages/vue/package.json
=> chore: bump ix version to 2.1.2

packages/documentation/src/pages/index.module.scss, packages/documentation/src/pages/index.tsx
When our documentation is viewed on a screen with an active display or browser zoom, the call-to-action buttons are not displayed correctly.
125% Zoom
The layout has been modified to ensure the buttons remain visible under all circumstances (zoom-levels).
125% Zoom
100% Zoom
Higher zoom levels need to be examined in the development environment, as images do not fully convey the details. The variation in colors is due to the discrepancies between the development and production environments.
Manual tests.
=> docs(home): fix call-to-action button alignment issues

packages/documentation/docs/design-kit/design-kit.md, packages/documentation/docs/guidelines/_theme-switching_code.md, packages/documentation/docs/guidelines/_theme-switching_styleguide.md, packages/documentation/docs/guidelines/theme-switching.md
=> docs: figma variables

.changeset/chilled-paws-run.md, packages/aggrid/scss/ix-aggrid.scss, packages/core/scss/legacy/components/_buttons.scss, packages/core/scss/legacy/components/_dropdown.scss, packages/core/src/components/blind/blind.scss, packages/core/src/components/drawer/drawer.scss, packages/core/src/components/event-list-item/event-list-item.scss, packages/core/src/components/expanding-search/expanding-search.scss, packages/core/src/components/menu-about-news/menu-about-news.scss, packages/core/src/components/menu-avatar/menu-avatar.scss, packages/core/src/components/menu/burger-menu.scss, packages/core/src/components/menu/menu.scss, packages/core/src/components/toggle/toggle.scss, packages/core/src/components/tree-item/tree-item.scss
- All CSS transitions use custom properties for timing values now
-
=> refactor(core): use custom properties for css transition times

packages/documentation/docs/controls/_content-header_code.md, packages/documentation/docs/controls/_content-header_styleguide.md, packages/documentation/docs/controls/content-header.md
No UX documentation for Content Header 
IX-502
UX documentation for Content header
=> docs(content-header): add ux styleguide

.changeset/cool-zebras-joke.md, packages/core/src/components/dropdown/dropdown.tsx
GitHub Issue Number: Closes #1240
=> fix(core/dropdown): add null check for trigger element

.github/workflows/pr.yml
React is currently not included in the unittests.
React is now included in the unittests.
X
=> fix: adapt pr pipeline to include react in unittests

.changeset/cyan-plums-build.md, packages/core/src/components/event-list-item/event-list-item.tsx
GitHub Issue Number: IX-968
-
-
=> fix(core/event-list-item): add aria-disabled attribute to list element

.changeset/quiet-pillows-jog.md, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/menu-about/menu-about.tsx
GitHub Issue Number: IX-559
-
-
=> docs(core/menu-about): update jsdocs

packages/angular-test-app/tsconfig.json, packages/angular/package.json, packages/react/package.json, packages/vue/package.json, pnpm-lock.yaml
=> build(angular): rxjs as devDependency to avoid type resolution conflicts

.changeset/rare-eagles-laugh.md, packages/core/src/components/group-item/group-item.scss
…d by user
- group-item cursor is default which is not correct
GitHub Issue Number: #1207 
- initially, group item cursor is pointer
- and also, the user can override it because it inherits from host element
=> fix(core/group): use correct cursors

.changeset/hot-sloths-fold.md, packages/core/src/components/group/group-context-menu.scss
GitHub Issue Number: #1209
-
-
=> fix(core/group-context-menu): set default cursor

.changeset/gold-terms-develop.md, packages/core/src/components/group/group.tsx, packages/core/src/components/group/test/group.ct.ts
GitHub Issue Number: Closes #1206
Keep `<slot>` rendered to ensure items check can be fulfilled 
=> fix(core/group): show expand-collapse icon

.changeset/popular-crabs-reply.md, packages/core/src/components/tooltip/tooltip.tsx
GitHub Issue Number: Closes #1249 
Check if trigger element is defined before adding listeners
=> fix(core/tooltip): null before register event listener to trigger

.changeset/giant-ways-wave.md, packages/core/src/components/button/base-button.tsx, packages/core/src/components/button/test/button.ct.ts
GitHub Issue Number: #1259 
-
-
=> fix(core/base-button): set aria disabled

.changeset/giant-owls-explain.md, .github/workflows/pr.yml, packages/core/src/components/blind/blind.scss
GitHub Issue Number: Closes #1279
Using `flex-grow` to avoid wrapping if not necessary.
=> fix(core/blind): avoid unnecessary wrapping

packages/documentation/docs/controls/buttons/_button_styleguide.md, packages/documentation/docs/controls/buttons/_icon-button_styleguide.md
- add danger button description
- add ellipsis description
- add min-width description
=> docs(button): add danger button description

.changeset/thin-spiders-press.md, packages/angular/src/components.ts, packages/core/src/components.d.ts, packages/core/src/components/split-button/split-button.tsx, packages/vue/src/components.ts
GitHub Issue Number: IX-563
-
-
=> feat(core/split-button): add close behavior

.github/workflows/pr.yml, packages/core/component-doc.json, scripts/lint-build.sh
Check if after build command executed no generated files are missing
=> ci(workflow/pr): add build changes check

packages/documentation/scripts/download-theme.ts
=> docs(theme): update theme to latest beta

.changeset/cool-keys-shout.md, packages/react/package.json, packages/react/rollup.config.js
GitHub Issue Number: #1123 
- Remove commonjs
=> feat(react): remove commonjs support

.github/workflows/actions/turbo/action.yml, .github/workflows/build.yml, .github/workflows/pr.yml, package.json, packages/aggrid/package.json, packages/angular/package.json, packages/eslint-config-ix/index.js, packages/eslint-config-ix/package.json, packages/react/package.json, packages/vue/package.json, pnpm-lock.yaml, turbo.json
- Update to latest turbo version
=> chore: update to turbo v2

packages/documentation/docs/controls/_dropdown_code.md, packages/documentation/docs/controls/dropdown.md
=> docs(core/dropdown): split md files

packages/documentation/docs/controls/modal.md, packages/documentation/docs/release-info.md
=> docs(core): fix typos

.changeset/curvy-rockets-sneeze.md, packages/core/component-doc.json, packages/core/package.json, pnpm-lock.yaml
Prevent stencil/core to update to latest version:
- https://github.com/ionic-team/stencil/issues/5868
- https://github.com/ionic-team/stencil/issues/5780
=> fix(core): prevent minor update of stencil/core

packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/select/select.tsx, packages/core/src/components/select/test/select.ct.ts, packages/core/src/components/tab-item/tab-item.tsx, packages/core/src/components/tabs/tabs.tsx
GitHub Issue Number: #IX-1351
-
-
=> feat(core/select): allow prevention of events

packages/documentation/src/css/search.scss
fixed stylings to be consistent to website look&feel
-
-
=> docs(agolia): change search.scss

.changeset/tall-toes-yell.md, packages/core/src/components/dropdown/dropdown.tsx, packages/core/src/components/utils/application-layout/service.ts
GitHub Issue Number: Closes #1372 
=> fix(core/application-header): prevent chrome crash after resize window

.changeset/breezy-taxis-nail.md, packages/core/src/components/dropdown/dropdown.tsx
stop auto update when closing dropdown
=> fix(core/dropdown): stop auto update when closing dropdown

.changeset/modern-games-eat.md, packages/core/src/components/tabs/tabs.tsx, packages/core/src/components/tabs/test/tabs.ct.ts
- Next/previous arrows will only be visible if there is actual overflow
-
=> fix(core/tabs): re-render each time parent container changes size

.changeset/silly-insects-decide.md, packages/core/src/index.ts, packages/figma-plugin/package.json
GitHub Issue Number: Closes #1408
- Export `TypedEvent`
=> fix(core): re-export TypedEvent

.changeset/fuzzy-countries-jam.md, packages/core/src/components/select/select.tsx
GitHub Issue Number: Closes #1377 IX-1448
-
-
=> fix(core/select): set value before triggering event

packages/documentation/docs/installation/angular.md
=> docs(angular): add note about standalone components

packages/documentation/docs/faq.md, packages/documentation/sidebars.ts, packages/documentation/src/components/Accordion/accordion.scss, packages/documentation/src/components/Accordion/index.tsx, packages/documentation/src/css/custom.scss
=> docs(faq): add section

.github/workflows/issue-needs-repo.yml
=> ci(workflow): add default needs repro text

packages/documentation/docs/faq.md
=> docs(faq): add mobile section

packages/documentation/docusaurus.config.ts, packages/figma-plugin/src/figma.ts
=> docs(figma): add retry function after rate limit reached

.changeset/quiet-tools-study.md, packages/core/src/components/icon-toggle-button/icon-toggle-button.tsx
When using the icon-toggle-button a console.log message is emited.
- console.log was removed
there is no logic, ui, or test related change expected - therefore none of these are applicable.
=> fix(core/icon-toggle-button): remove console.log

.changeset/nice-pianos-serve.md, packages/core/src/components/icon-button/icon-button-mixin.scss, packages/core/src/components/spinner/spinner.scss, packages/core/src/components/spinner/spinner.tsx, packages/core/src/components/upload/upload.scss
GitHub Issue Number: Closes #1511, IX-1830
-
-
=> fix(core/spinner): move styling into shadow dom

packages/documentation/docs/controls/forms/_forms-field_code.mdx, packages/documentation/docs/controls/forms/_forms-field_style.mdx, packages/documentation/docs/controls/forms/_forms-layout_code.mdx, packages/documentation/docs/controls/forms/_forms-layout_style.mdx, packages/documentation/docs/controls/forms/_forms-validation_code.mdx, packages/documentation/docs/controls/forms/forms-field.md, packages/documentation/docs/controls/forms/forms-layout.md
Form chapters reordered introducing style and code tabs.
=> docs(forms): reorder form chapters

.changeset/large-cherries-attend.md, packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/category-filter/category-filter.tsx, packages/core/src/components/category-filter/test/category-filter.ct.ts, packages/vue/src/components.ts
=> feat(core/categroy-filter): add filter cleared event

packages/ionic-test-app/vite.config.ts
Copy only files that are needed to show ionic test app inside the documentation
=> chore(ionic-test-app): prevent copy complete theme project

.changeset/lazy-birds-dream.md, packages/angular/src/control-value-accessors/text-value-accessor.ts, packages/core/src/components.d.ts, packages/core/src/components/date-input/date-input.tsx, packages/core/src/components/field-label/field-label.tsx, packages/core/src/components/field-wrapper/field-wrapper.tsx, packages/core/src/components/input/input.fc.tsx, packages/core/src/components/input/input.tsx, packages/core/src/components/input/number-input.tsx, packages/core/src/components/input/textarea.tsx, packages/core/src/components/select/select.tsx, packages/core/src/components/utils/make-ref.ts
GitHub Issue Number: Closes #1594
- Fix issue were controlRef is used with a native element instead of MakeRef
=> fix(core/select): replace element ref with make-ref function

.changeset/real-timers-relate.md, packages/core/package.json, packages/core/src/components/tree-item/tree-item.tsx, packages/core/src/components/tree/tree.tsx, packages/core/src/components/utils/lazy-list/index.ts, packages/core/src/components/utils/lazy-list/lazy.ts, pnpm-lock.yaml
GitHub Issue Number: #1385 
Remove hyperlist as a dependency, to avoid to level `document` access
=> fix(core): remove hyperlist dependency

.changeset/quick-bugs-thank.md, packages/aggrid/scss/ix-aggrid.scss, packages/aggrid/tests/basic.html, packages/aggrid/tests/pagination.html, packages/html-test-app/src/preview-examples/aggrid.html
=> fix(ag-grid): pin test version and hide border bottom

packages/documentation/docs/language/punctuation.md
=> Fix don't for Tuesday guideline

packages/core/src/tests/workflow-steps/workflow-steps.e2e.ts
- workflow-steps vrt often fails
GitHub Issue Number: [-]
- replace waitForSelector with the locator, that additionally check some stuff to guarantee the component is ready
=> fix: make workflow-steps vrt less flaky

packages/documentation/docs/roadmap.md
New illustration and text for Roadmap
=> docs: Update roadmap 2025

.github/workflows/build.yml, .github/workflows/pr.yml, packages/core/src/tests/blind/basic/index.html
Fix issue of uploading artifacts after update artifacts action to v4
=> ci(visual-testing): resolve artifact upload issue

.changeset/hot-ligers-shout.md, packages/angular/src/components.ts, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/application-header/application-header.tsx, packages/core/src/components/application-header/test/application-header.ct.ts, packages/core/src/components/menu/menu.tsx, packages/vue/src/components.ts
GitHub Issue Number: IX-1137
-
-
=> feat(core/application-header|menu): add open app switch event

packages/html-test-app/package.json, packages/html-test-app/src/preview-examples/aggrid.html, pnpm-lock.yaml
GitHub Issue Number: Closes #1640 
- Replace CDN import with local import
- Use latest version for preview
=> docs(html-test-app/aggrid): replace cdn with bundled dependency

packages/documentation/docs/installation/angular.md
- The documentation doesn't mention support for standalone components
GitHub Issue Number: **IX-2333**
- The documentation now mentions support for standalone components
=> docs(angular): describe angular standalone setup

.husky/commit-msg, CONTRIBUTING.md, package.json, pnpm-lock.yaml
Remove `pre-commit` check for commit message. Commits inside a PR should be readable but don't have to follow the guide. 
After PR is reviewed the PR will be squashed and dont have a history later on.
=> build: remove husky commit hooks

package.json, packages/core/component-doc.json, patches/@stencil__core@4.27.0.patch, pnpm-lock.yaml
Quick patch until https://github.com/ionic-team/stencil/pull/6175 is merged and released
=> chore(core): use patched version of stencil to prevent hydration errors

.gitignore, packages/aggrid/package.json, packages/angular-standalone-test-app/package.json, packages/angular-test-app/package.json, packages/angular/package.json, packages/core/package.json, packages/documentation/docusaurus.config.ts, packages/documentation/package.json, packages/documentation/scripts/generate-markdown.ts, packages/documentation/src/pages/index.tsx, packages/documentation/src/theme/Root.tsx, packages/html-test-app/package.json, packages/ionic-test-app/package.json, packages/react-test-app/package.json, packages/react/package.json, packages/storybook-docs/package.json, packages/vue-test-app/package.json, packages/vue/package.json, pnpm-lock.yaml
Integrate latest ix-icons snapshot with enhanced logging functionality and latest stencil runtime
=> chore: update to latest ix-icon version

renovate.json
GitHub Issue Number: #IX-1231
-
-
=> ci(renovate): add config file

packages/documentation-redesign/docusaurus.config.ts, packages/documentation-redesign/src/scss/components/_navLink.scss, packages/documentation-redesign/src/scss/custom.scss
Fixes IX-2240
> [!IMPORTANT]
> Workflows will not run because target branch exclude `documentation` package from workspace
>
> Use `pnpm start --filter documentation-redesign` to start redesign documentation
=> docs: add shortcut to navbar

.github/workflows/pr.yml
=> ci(renovate): check for correct user login

.changeset/quick-rabbits-fail.md, packages/core/src/components/date-picker/date-picker-component.ts
As discussed small PR to add the new prop to the Datepicker interface. Also fixed some typos.
=> fix(core/date-picker): Add new prop to interface

.changeset/tame-emus-poke.md, BREAKING_CHANGES/v3.md, packages/documentation/docs/home/migration/3_0_0/index.md
- Fix missing breaking change of #1630
- Fix wrong changeset category of #1630
=> docs: add breaking changes guide regarding echart changes

.changeset/short-impalas-joke.md, packages/core/src/components/select/select.tsx, packages/core/src/components/utils/input/index.ts
=> fix(core/input): add promise<void> to return type of interface method

packages/documentation/docusaurus.config.ts, packages/documentation/sidebars.ts, packages/documentation/src/components/CodePreview/index.tsx, packages/documentation/src/components/Playground/index.tsx, packages/documentation/src/components/Playground/styles.module.css, packages/documentation/src/components/UI/Button/styles.module.css, packages/documentation/src/components/UI/FrameworkSelection/index.tsx, packages/documentation/src/components/UI/OpenStackblitz/index.tsx, packages/documentation/src/components/UI/Pill/index.tsx, packages/documentation/src/components/UI/Pill/styles.module.css, packages/documentation/src/components/UI/Tags/base.module.css, packages/documentation/src/components/UI/ThemeSelection/index.tsx, packages/documentation/src/components/UI/ThemeVariantToggle/index.tsx, packages/documentation/src/scss/custom.scss, packages/documentation/src/scss/overwrite/_navbar.scss
GitHub Issue Number: IX-2562
-
-
=> docs: use siemens fonts

packages/documentation/package.json, packages/documentation/src/theme/SiteMetadata/index.tsx, packages/documentation/src/theme/prism-include-languages.ts, pnpm-lock.yaml
=> docs: add Vue syntax highlighting

.changeset/grumpy-phones-relax.md, packages/core/component-doc.json, packages/core/src/components.d.ts, packages/core/src/components/validation-tooltip/validation-tooltip.scss, packages/core/src/components/validation-tooltip/validation-tooltip.tsx
GitHub Issue Number: Fixes #1314
- Added deprecated annotation
- Not added any visual-regression test due to deprecation annotation
=> fix(core/validation-tooltip): increase zIndex for validation tooltip

packages/core/scss/_core.scss, packages/documentation/docs/guidelines/accessibility.md, packages/documentation/docs/guidelines/designprinciples.md, packages/documentation/docs/guidelines/overview.md, packages/documentation/docs/home/overview.md, packages/documentation/sidebars.ts
=> docs: design principles

.github/workflows/deploy-gh-2.7-pages.yml, .github/workflows/deploy-gh-pages.yml, packages/documentation/version-deployment.json
- Prepare documentation switch to v3 version (#1642)
=> ci(pages): publish documentation into sub folder

packages/documentation/src/components/IconsPreview/Icons.module.css
=> docs(icons): update hash-link style

README.md
The link isn't working / 404.
- the link works
only change in readme
=> docs(README): fix link

packages/documentation/docs/home/migration/3_0_0/index.md
=> docs: update v3 breaking changes link

packages/documentation/package.json, packages/documentation/scripts/build.ts, packages/documentation/scripts/templates/playground-files.mustache, packages/documentation/scripts/templates/playground-markdown.mustache, pnpm-lock.yaml
GitHub Issue Number: #1901
Add angular standalone generation. Documentation integration: https://github.com/siemens/ix-docs/pull/9
=> docs: add angular standalone into playground generation

.changeset/happy-socks-run.md, .changeset/short-trains-begin.md, packages/angular/standalone/src/providers/modal.ts, packages/angular/standalone/src/providers/toast.ts
GitHub Issue Number: Fixes #1911
- Define custom components before usage.
=> fix(angular): define custom elements before service tries to use it

README.md
GitHub Issue Number: #1937 
-
-
=> docs(readme): udpate quickstart link

packages/core/playwright.config.ts, packages/core/src/components/application-header/test/application-header.ct.ts, packages/core/src/components/date-picker/test/date-picker.ct.ts, packages/core/src/components/dropdown/test/dropdown.ct.ts, packages/core/src/components/flip-tile/flip-tile.tsx, packages/core/src/components/flip-tile/test/flip-tile.ct.ts, packages/core/src/components/utils/test/animation.ct.ts, packages/core/src/components/workflow-steps/test/workflow-steps.ct.ts, packages/core/src/tests/utils/test/page.ts, packages/core/tsconfig.test.json
- Disable animations for all tests by default (using PR https://github.com/siemens/ix/pull/2075)
=> refactor: improve flaky component tests

CONTRIBUTING.md
contribution.md node version is updated to v22.19.0 same as package.json
=> [2184]: fix(contribution.md): update node info
